### ISSUE TITLE
Adapt meteor 1.3 file structure guidelines

### ISSUE THREAD

**Issue by Dev1an** [JeroenBe/SnapTwit#1]
Hi Jeroen! I saw you are still relying on 'lib' folders to ensure correct load order. Maybe you can start using the new [file structure guidelines](http://guide.meteor.com/structure.html#javascript-structure) from the [Meteor Guide](http://guide.meteor.com/).

**Comment by JeroenBe** [comment]
Noted, refactoring has started!
