### ISSUE TITLE
Install momentjs via NPM

### ISSUE THREAD

**Issue by Dev1an** [jeroenbe/SnapTwit#3]
Meteor is shifting more and more towards nodejs modules instead of meteor packages. So instead of relying on packages that wrap node modules, it's better to use the node modules directly.

Check the meteor guide [Atmosphere vs NPM](http://guide.meteor.com/atmosphere-vs-npm.html)

**Comment by JeroenBe** [comment]
Thanks Dev1an! love the tips, keep 'em comming 😄

**Comment by Dev1an** [comment]
This is the mail system at host lotootevai.mailfwd.taloha.net.

I'm sorry to have to inform you that your message could not
be delivered to one or more recipients. It's attached below.

For further assistance, please send mail to postmaster.

If you do so, please include this problem report. You can
delete your own text from the attached returned message.

                   The mail system

<DAMIAAN@DPRO.BE>: host DPRO.BE[67.20.78.203] said: 550-Message rejected
    because (lotootevai.mailfwd.taloha.net) 550 [209.126.220.134]:53655 is
    blacklisted. (in reply to RCPT TO command)

**Comment by Dev1an** [comment]
Dear Jeroen,

The email sent to info@devian.tk with subject
"Re: [JeroenBe/SnapTwit] Install momentjs via NPM (#3)"
will be delivered as soon as possible.

Your email address is automatically added to the
recipients 'whitelist'. This means for further
emails to info@devian.tk, you will not receive a delivery
notification again.

TK MAILIAS
*************************************************
Looking for a way to Protect Your Identity and 
for a great no-more-spam solution for your email
address reply@reply.github.com? Sign up for TK Mailias.

It's free! Please visit http://www.mail.tk/
